### ISSUE TITLE
Left align form elements in a grid

### ISSUE THREAD

**Issue by dsurrao** [dsurrao/oncdeckredux#5]
Also consider left aligning the form elements on a grid. You don't want them to flow together horizontally like text. 

They should be spaced incrementally apart as distinct choices and have enough space that they are easily tappable. 

![Screenshot 2020-06-26 07 46 30](https://user-images.githubusercontent.com/5474474/85934306-23585300-b8af-11ea-9d7b-a7b29d00b9ce.png)

![Screenshot 2020-06-26 07 47 18](https://user-images.githubusercontent.com/5474474/85934351-7d591880-b8af-11ea-948f-cdc5f96228e5.png)

**Comment by BenjaminGHo** [comment]
@dsurrao, how does this look?

![image](https://user-images.githubusercontent.com/7934706/87881940-be35e000-c9ca-11ea-9176-689854d7325d.png)

I made a CSS change to the element.  Instead of `display: inline-block`, I made it `display: block`.  Then I added some padding to the element.

**Comment by dsurrao** [comment]
Hi @BenjaminGHo that looks great! Thanks.

**Comment by dsurrao** [comment]
Closed with this PR: #6
